version: '3'
services:
  python:
    # image: python:3.4
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 3000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myopt
      - POSTGRES_PASSWORD=myopt
      - POSTGRES_DB=myopt_dev
    ports:
      - 5432:5432

volumes:
  postgres_data: