# Generated by Django 4.2 on 2023-04-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('little_title', models.CharField(max_length=500)),
                ('big_title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='slider_images')),
            ],
            options={
                'verbose_name': 'Index Sliders',
            },
        ),
    ]
