# Generated by Django 4.2 on 2023-04-24 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('experience', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Who We Are',
                'verbose_name_plural': 'Who We Are',
            },
        ),
        migrations.CreateModel(
            name='WhoTitle2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_2', to='blog.whoweare')),
            ],
        ),
        migrations.CreateModel(
            name='WhoTitle1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_1', to='blog.whoweare')),
            ],
        ),
    ]
