# Generated by Django 4.2 on 2023-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_whoweare_whotitle2_whotitle1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whotitle1',
            options={'verbose_name': 'Title 1', 'verbose_name_plural': 'Title 2'},
        ),
        migrations.AlterModelOptions(
            name='whotitle2',
            options={'verbose_name': 'Title 2', 'verbose_name_plural': 'Title 2'},
        ),
        migrations.AddField(
            model_name='whoweare',
            name='title1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='title2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
