# Generated by Django 4.2 on 2023-04-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='galleries')),
                ('link', models.CharField(max_length=3000)),
                ('link_name', models.CharField(max_length=300)),
            ],
        ),
    ]
