# Generated by Django 4.2 on 2023-04-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=1500, verbose_name='Saytın başlığı')),
                ('number', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Nömrə')),
                ('adress', models.CharField(max_length=1500, null=True, verbose_name='Ünvan')),
                ('g_adress', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Google Map linki')),
                ('logo', models.FileField(blank=True, upload_to='general_settings', verbose_name='logo(138x35)')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='general_settings', verbose_name='favicon(100x100)')),
                ('footer_logo', models.FileField(blank=True, help_text='Saytın aşağısındakı logo', null=True, upload_to='general_settings', verbose_name='Footer logo(150x38)')),
                ('facebook', models.CharField(blank=True, max_length=1500, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=1500, verbose_name='Linkedin')),
                ('instagram', models.CharField(blank=True, max_length=1500, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Twitter')),
                ('location', models.CharField(max_length=1500, null=True, verbose_name='Əlaqə Lokasiya')),
                ('number_1', models.CharField(max_length=100, null=True, verbose_name='Elaqe Nomresi')),
                ('number_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Elaqe Nomresi 2 Optional')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email daxil edin')),
                ('comment_user_image', models.ImageField(null=True, upload_to='comment_user', verbose_name='Komment User Profil Sekili(70x70)')),
                ('footer_text', models.TextField(null=True, verbose_name='Footer Ucun tekst')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'General Settings',
            },
        ),
    ]
