# Generated by Django 4.2 on 2023-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_generalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
