# Generated by Django 4.2 on 2023-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_slug_alter_articlecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
