# Generated by Django 4.2 on 2023-04-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_author_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
