# Generated by Django 4.2 on 2023-04-25 12:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
