# Generated by Django 4.2 on 2023-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_service_slug_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='video_image',
            field=models.ImageField(null=True, upload_to='VideoImage'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='video_link',
            field=models.TextField(null=True),
        ),
    ]
