# Generated by Django 4.2 on 2023-04-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_whyus_video_image_whyus_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AboutOffers')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
            ],
        ),
    ]
