# Generated by Django 4.2 on 2023-04-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='comment_user_image',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='location',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='number_1',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='number_2',
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='email',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Email'),
        ),
    ]
