# Generated by Django 4.0.10 on 2023-05-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_appointment_message_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='youtube',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Youtube'),
        ),
    ]
