# Generated by Django 4.0.10 on 2023-05-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_rename_linkedin_generalsettings_tiktok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsettings',
            old_name='tiktok',
            new_name='linkedin',
        ),
    ]
