# Generated by Django 4.0.10 on 2023-05-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_rename_tiktok_generalsettings_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_banner',
            field=models.ImageField(null=True, upload_to='service_banner'),
        ),
    ]
