# Generated by Django 4.0.10 on 2023-05-22 16:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_article_article_banner_article_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='whyoffers',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
