# Generated by Django 4.0.10 on 2023-05-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_whoweare_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoweare',
            name='banner',
        ),
    ]
