# Generated by Django 4.0.10 on 2023-05-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_remove_whoweare_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='number',
        ),
    ]
