# Generated by Django 4.0.10 on 2023-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_remove_generalsettings_number_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='number_1',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Nömrə'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='number_2',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Nömrə'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='number_3',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Nömrə'),
        ),
    ]
