# Generated by Django 4.0.10 on 2023-05-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_generalsettings_number_1_generalsettings_number_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='number_1',
        ),
    ]
