# Generated by Django 4.0.10 on 2023-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_remove_generalsettings_number_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='number_1',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Nömrə'),
        ),
    ]
