# Generated by Django 4.0.10 on 2023-06-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_alter_certificate_certificate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsettings',
            old_name='linkedin',
            new_name='tiktok',
        ),
    ]
