# Generated by Django 4.0.10 on 2023-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_rename_linkedin_generalsettings_tiktok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='tiktok',
            field=models.CharField(blank=True, max_length=1500, verbose_name='TikTok'),
        ),
    ]
