# Generated by Django 4.0.10 on 2023-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_alter_generalsettings_tiktok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.FileField(default='', upload_to='certificate_image'),
            preserve_default=False,
        ),
    ]
