# Generated by Django 4.0.10 on 2023-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_alter_certificate_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='mobile_logo',
            field=models.FileField(blank=True, help_text='Mobile logo', null=True, upload_to='general_settings', verbose_name='Mobile logo(150x38)'),
        ),
    ]
