# Generated by Django 4.0.10 on 2023-06-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_alter_appointment_email_alter_appointment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
