# Generated by Django 4.0.10 on 2023-07-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_alter_appointment_email_alter_appointment_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexslider',
            name='big_title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='big_title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='little_title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='little_title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
