# Generated by Django 4.0.10 on 2023-07-04 23:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_indexslider_big_title_az_indexslider_big_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='experience_az',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='experience_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='title1_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='title1_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='title2_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='title2_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
