# Generated by Django 4.0.10 on 2023-07-05 08:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_whoweare_experience_az_whoweare_experience_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutoffers',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutoffers',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutoffers',
            name='title_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutoffers',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='message_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='category_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.articlecategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.articlecategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='context_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='context_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_az',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='name_az',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='link_name_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='link_name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='adress_az',
            field=models.CharField(max_length=1500, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='adress_ru',
            field=models.CharField(max_length=1500, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='footer_text_az',
            field=models.TextField(null=True, verbose_name='Footer Ucun tekst'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='footer_text_ru',
            field=models.TextField(null=True, verbose_name='Footer Ucun tekst'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_title_az',
            field=models.CharField(max_length=1500, null=True, verbose_name='Saytın başlığı'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_title_ru',
            field=models.CharField(max_length=1500, null=True, verbose_name='Saytın başlığı'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_az',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serviceoffers',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceoffers',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='whyoffers',
            name='text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='whyoffers',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='whyoffers',
            name='title_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whyoffers',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
