# Generated by Django 4.0.10 on 2023-07-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_aboutoffers_text_az_aboutoffers_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whotitle1',
            options={'verbose_name': 'Title 1', 'verbose_name_plural': 'Title 1'},
        ),
        migrations.RenameField(
            model_name='whotitle1',
            old_name='who',
            new_name='who1',
        ),
        migrations.RenameField(
            model_name='whotitle2',
            old_name='who',
            new_name='who2',
        ),
    ]
