# Generated by Django 4.0.10 on 2023-07-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_alter_whotitle1_options_rename_who_whotitle1_who1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whotitle1',
            name='name_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whotitle1',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whotitle2',
            name='name_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whotitle2',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
