# Generated by Django 4.0.10 on 2023-07-11 08:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_aboutoffers_text_az_aboutoffers_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[410, 410], upload_to='galleries'),
        ),
    ]
