# Generated by Django 4.0.10 on 2023-07-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(default=1, upload_to='galleries'),
            preserve_default=False,
        ),
    ]
