# Generated by Django 4.0.10 on 2023-07-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.FileField(default=1, upload_to='certificate_image'),
            preserve_default=False,
        ),
    ]
