# Generated by Django 4.2.6 on 2023-10-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0070_alter_certificate_certificate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloq_Description_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Bloq_Keyword_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Bloq_Title_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='BodySeoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=50000, null=True)),
                ('keyword', models.TextField(blank=True, max_length=50000, null=True)),
            ],
            options={
                'verbose_name': 'Əlaqə SEO',
                'verbose_name_plural': 'Əlaqə SEO',
            },
        ),
        migrations.CreateModel(
            name='Gallery_Description_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_Keyword_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_Title_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='HeadSeoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Description_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Keyword_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Title_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Services_Description_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Services_Keyword_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Services_Title_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutoffers',
            name='text_az',
        ),
        migrations.RemoveField(
            model_name='aboutoffers',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='aboutoffers',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='aboutoffers',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='message_az',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='context_az',
        ),
        migrations.RemoveField(
            model_name='article',
            name='context_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message_az',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject_az',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject_ru',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='link_name_az',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='link_name_ru',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='adress_az',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='adress_ru',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='footer_text_az',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='footer_text_ru',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='site_title_az',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='site_title_ru',
        ),
        migrations.RemoveField(
            model_name='indexslider',
            name='big_title_az',
        ),
        migrations.RemoveField(
            model_name='indexslider',
            name='big_title_ru',
        ),
        migrations.RemoveField(
            model_name='indexslider',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='indexslider',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='indexslider',
            name='little_title_az',
        ),
        migrations.RemoveField(
            model_name='indexslider',
            name='little_title_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='text_az',
        ),
        migrations.RemoveField(
            model_name='service',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='serviceoffers',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='serviceoffers',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_az',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='position_az',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='position_ru',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='text_az',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='whotitle1',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='whotitle1',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='whotitle2',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='whotitle2',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='experience_az',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='experience_ru',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='text_az',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='title1_az',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='title1_ru',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='title2_az',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='title2_ru',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='whoweare',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='whyoffers',
            name='text_az',
        ),
        migrations.RemoveField(
            model_name='whyoffers',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='whyoffers',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='whyoffers',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='text_az',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='article',
            name='alt_for_foto',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_for_foto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='alt_for_foto',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='keyword',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=3000),
        ),
    ]
